### PR TITLE
ocicni: add support of specifying static MACs

### PR DESCRIPTION
**Pull request by filak-sap**
Add the parameter MAC to CNI_ARGS.

I copied the approach from the plugin tunning and github.com/intel/multus-cni.

### CODE REVIEW

**Comment by filak-sap** [comment]
Ouch - I got 404 when opening https://github.com/cri-o/ocicni/blob/master/CONTRIBUTING.md as suggested in the comment above.

**Comment by mheon** [comment]
This is a request from the Podman side, to allow containers to specify custom MAC addresses in the same way they specify custom IPs

**Comment by mheon** [comment]
@dcbw Think you misspelled the `/approve`

**Comment by rhatdan** [comment]
Worth a try
/approve

**Comment by rhatdan** [comment]
@rajatchopra @sameo @dcbw @mrunalp could one of you /approve this so we can get it into podman?

**Pull request merged**
