### PR TITLE
[RFC] ocicni: always monitor net dir

### PR DESCRIPTION
**Pull request by schu**
Currently, the net dir (usually `/etc/cni/net.d`) is only monitored for
new network configuration files during runtime iff it does not contain
any files during CNI initialization (`InitCNI`):

* If a valid configuration file is found during initialization, only
  exactly this plugin will be loaded and used throughout.
* If the directory contains only invalid configuration files or in the
  event on an error, a noop plugin is returned.

It's not unusual though for the net dir to contain default network
configuration or or fallback at first (for example when the cri-o
systemd unit is started) and to be updated later (for example by a
network plugin like flannel). At present, the update of the directory
would not be detected since the monitor routine is not started in any
case.

Instead, always start the monitor routine and never return a noop
plugin. This way new default configuration will be picked up immediately
or, if containing errors, lead to an error message in the log.

Signed-off-by: Michael Schubert <michael@kinvolk.io>

### CODE REVIEW

**Comment by schu** [comment]
I had `99-loopback.conf` in my `/etcd/cni/net.d` directory and was wondering why cri-o didn't pick up on the flannel install after.

**Comment by schu** [comment]
Friendly ping :) Thoughts?

**Comment by dcbw** [comment]
So the only issue with always monitoring is that this could lead to a mismatch between ADD/DEL for a given container.  For example, ADD happens with a given network.  Next, something adds a new CNI config that becomes the default network.  Now DEL for that same container will use the new network, which would be wrong.

Also, note that you don't need any loopback configs in /etc/cni/net.d, as ocicni will internally always add a loopback network anyway.

That said, the noop plugin thing should die because if the CNI configs have errors in them, that leads to a noop plugin returned and container setup/teardown succeeding with no networking.

**Comment by dcbw** [comment]
@schu my thought was something like https://github.com/cri-o/ocicni/pull/11

**Comment by schu** [comment]
@dcbw thanks, #11 looks good to me from a cursory look.

But I wonder if the monitor routine should stop here: https://github.com/cri-o/ocicni/blob/490e966bd0268e3145f0f4792ec5e5dd91ef28fe/pkg/ocicni/ocicni.go#L121-L122 As is it has the same problem as described above (potential ADD/DEL mismatch), I think.

**Pull request closed without merging**
