### PR TITLE
Sync pod operations

### PR DESCRIPTION
**Pull request by dcbw**
@mrunalp @Random-Liu 

This is essentially a port of the Kubernetes PluginManager code from https://github.com/kubernetes/kubernetes/pull/37036.  See also https://github.com/kubernetes-incubator/cri-o/pull/837

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by Random-Liu** [comment]
@dcbw Thanks!

**Comment by Random-Liu** [comment]
@dcbw Just for my education, what is the reason behind serialization pod `SetupPod` and `Teardown`?

CNI operations are not thread safe? Concurrent `Teardown` may cause issue?

**Pull request merged**
