### PR TITLE
ocicni: find networks to delete from cache

### PR DESCRIPTION
**Pull request by dcbw**
Instead of requiring the runtime to save network attachment state
for correct network teardown, allow the runtime to pass an empty
list of networks. Passing an empty list reads the attachments
from cache and tears them down using that information.

I anticipate the read-all-networks-from-cache functionality will
make it upstream to CNI soon, but for now keep it in ocicni.

This PR is more useful for runtimes like CRIO that only care about a single network and don't need to save a ton of state. But runtimes like podman may wish to keep that state (for 'inspect' or other operations) and can pass it back on teardown.

@mrunalp @mccv1r0 @mars1024

### CODE REVIEW

**Comment by dcbw** [comment]
@squeed this PR would be a quicker path for CRIO since it only cares about a single network

**Comment by mars1024** [comment]
@dcbw  A good PR to make CNI DEL more "smart", but I think you forgot to bump up libcni, because only the latest libcni support to cache ifName and networkName... 
I pull a new PR #60 to resolve this.

**Comment by mars1024** [comment]
@dcbw @squeed Could you pay attention to the problem which I mentioned above?

**Pull request merged**
